apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-app
  name: hello-app
  namespace: sabeerz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
        - image: 'gcr.io/google-samples/hello-app:1.0'
          name: hello-app
          ports:
            - containerPort: 8080


